version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_procedures
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
      - ./postgresql_procedures.sql:/docker-entrypoint-initdb.d/02-create-procedures.sql
    restart: unless-stopped

volumes:
  postgres_data: 