version: '3.8'

services:
  postgres_procedures:
    image: postgres:15
    container_name: postgres_procedures
    environment:
      POSTGRES_DB: defense_logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_defense_logistics_tables.sql:/docker-entrypoint-initdb.d/01-create-tables.sql
      - ./defense_logistics_procedures.sql:/docker-entrypoint-initdb.d/02-create-procedures.sql
    restart: unless-stopped

volumes:
  postgres_data: 